# Generated by Django 2.1.4 on 2019-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=270)),
                ('slug', models.SlugField(unique=True)),
                ('publicatin_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufactuar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('publication_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=290)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('details', models.TextField()),
                ('price', models.SmallIntegerField()),
                ('quantity', models.SmallIntegerField()),
                ('stock_level', models.SmallIntegerField()),
                ('publication_status', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=True, to='app.category')),
                ('manufactuar_id', models.ForeignKey(on_delete=True, to='app.Manufactuar')),
            ],
        ),
    ]
