# Generated by Django 2.1.4 on 2018-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='course',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='contact_no',
            field=models.IntegerField(default=10),
        ),
    ]
