# Generated by Django 2.1.4 on 2018-12-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181217_0656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_course',
        ),
    ]
