# Generated by Django 2.1.4 on 2018-12-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
