# Generated by Django 2.1.4 on 2018-12-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='r_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
