# Generated by Django 2.1.4 on 2018-12-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_leave_r_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_leave',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='r_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
