# Generated by Django 2.1.4 on 2018-12-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181221_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_classes',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='add_daily_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_starting_time', models.TimeField()),
                ('class_ending_time', models.TimeField()),
                ('total_duration', models.IntegerField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_classes')),
            ],
        ),
        migrations.CreateModel(
            name='faculity_registration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('exp', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.AddField(
            model_name='add_daily_timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculity_registration'),
        ),
    ]
