# Generated by Django 2.1.4 on 2018-12-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181222_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculity_registration',
            name='exp',
            field=models.IntegerField(),
        ),
    ]
