# Generated by Django 2.1.4 on 2018-12-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181222_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('des', models.CharField(max_length=100)),
            ],
        ),
    ]
