# Generated by Django 2.1.4 on 2018-12-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
