# Generated by Django 2.1.4 on 2018-12-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181224_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_contact',
            fields=[
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='file_upload',
        ),
    ]
