# Generated by Django 2.1.4 on 2018-12-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181224_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_classes',
            old_name='class_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='add_classes',
            old_name='class_name',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='add_classes',
            name='course_duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_daily_timetable',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_classes', to_field='class_id'),
        ),
    ]
