# Generated by Django 2.1.4 on 2018-12-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181224_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_classes',
            old_name='course_id',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='add_classes',
            old_name='course_name',
            new_name='class_name',
        ),
        migrations.RemoveField(
            model_name='add_classes',
            name='course_duration',
        ),
        migrations.AlterField(
            model_name='add_daily_timetable',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_classes'),
        ),
    ]
