# Generated by Django 2.1.5 on 2019-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
